export const PIC_MAP = {
  "PRAPANCA PADEL COURT ROOM": {
    ARCH: "-",
    INTR: "-",
    DRFT: "-",
    PM: "-",
    PGWS: "-",
  },
  "SENTUL WELLNESS CENTER": {
    ARCH: "Maladzi",
    INTR: "Biba",
    DRFT: "Rifky",
    PM: "-",
    PGWS: "-",
  },
  "JOGJA SPORT CENTER": {
    ARCH: "Wahyu",
    INTR: "Welia",
    DRFT: "-",
    PM: "-",
    PGWS: "-",
  },
  "WELLNESS & LIFESTYLE PIK 1": {
    ARCH: "Maladzi",
    INTR: "Biba",
    DRFT: "Aldy",
    PM: "-",
    PGWS: "-",
  },
  "PRESTIGE PADEL": {
    ARCH: "-",
    INTR: "-",
    DRFT: "-",
    PM: "-",
    PGWS: "Nassar",
  },
  "PADELIO 2": {
    ARCH: "Wahyu",
    INTR: "Welia",
    DRFT: "Aldi",
    PM: "-",
    PGWS: "Fahrezi Abdad",
  },
  "PADELIO": {
    ARCH: "Wahyu",
    INTR: "Welia",
    DRFT: "Aldi",
    PM: "-",
    PGWS: "Fahrezi Abdad",
  },
  "OSSO": {
    ARCH: "Juita",
    INTR: "Biba",
    DRFT: "Aldi",
    PM: "-",
    PGWS: "Boy",
  },
  "INTERIOR LAKESIDE 112": {
    ARCH: "Wahyu",
    INTR: "Sonia",
    DRFT: "Danu",
    PM: "-",
    PGWS: "Farhat",
  },
  "LITTLE SINBAD": {
    ARCH: "-",
    INTR: "-",
    DRFT: "-",
    PM: "-",
    PGWS: "-",
  },
  "VRDE VILLA DUTA": {
    ARCH: "Wahyu",
    INTR: "Welia",
    DRFT: "Rifky",
    PM: "-",
    PGWS: "Salim",
  },
  "AP HOUSE": {
    ARCH: "Juita",
    INTR: "Sonia",
    DRFT: "Rifky",
    PM: "-",
    PGWS: "Farhat",
  },
  "MR. HERU'S HOUSE": {
    ARCH: "Zahra",
    INTR: "Sonia",
    DRFT: "Danu",
    PM: "-",
    PGWS: "Piye",
  },

} as const;
export type ProjectName = keyof typeof PIC_MAP;
export type ProjectPIC = typeof PIC_MAP[ProjectName];
